Add Minor Features
stats4sd/aec_portfolio pull request #49
Opened 2023-05-11 14:37 UTC by dan-tang-ssd

I added some minor features as below:

My Role page
 - This is available for institutional admin / assessor / member only. Site admin and site manager cannot access it because they do not belong to any institution.
 - It shows organisation name, user name, role name.
 - It shows a link to "Request to leave an institution"
 - It shows a link to "Request to remove everything for institution"

---

Request to leave an institution
  - Optional to remove personal data (just to overwrite users.name, users.email with dummy value)
  - Delete the corresponding organisation_members record
     - user still can login but unable to enter main menu because user does not belong to any institution now

---

Request to remove everything for institution
  - Once submit, a new removal_requests record will be created with below items:
     - Organisation id, name, requester id, name, email
     - These data values will be kept for future enquiry or reference after everything is removed for an institution
     - Nothing change after submitting this request, user can login and use data platform as usual
   
  - Note: Email template will be developed once confirmed email will be sent for which actions

P.S. Text content, UI look and feel to be revised

---

Removal Request CRUD panel
 - create / update / delete are disabled
 - preview is enabled
 - added custom buttons for Cancel, Remind, Confirm, Remove Everything
 - status:
    - REQUESTED: data removal request has been submitted by institutional admin
    - CANCELLED: site admin / site manager manually click Cancel button to cancel removal request
    - REMINDER_SENT: site admin / site manager manually click Remind button to send reminder email to requester
    - FINAL_CONFIRMED: site admin / site manager manually click Confirm button to final confirm data removal (Suppose requester should reply reminder email to site admin / site manager to final confirm data removal request)
    - EVERYTHING_REMOVED: site admin / site manager manually click Remove Everything button, all related records for an institution removed in database

Currently all operations are performed manually by site admin / site manager.
As the precise procedure is subject for discussion (this may take a long time). I have developed the core workflow and data removal programs only.

2023-05-11 14:42 UTC, dan-tang-ssd commented
Here are some screen shots FYI:

My Role page
![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/21e0ad5b-d361-4829-a40f-6bee9dd470a2)

Request to leave an institution
![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/5dd5924e-1032-4b25-8339-51e87fa1ae72)

Request to remove everything for institution
![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/d9f08370-e5b7-4a61-8466-5cd4e965de78)

Removal Requests CRUD
![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/0033dff0-5595-4f8a-acc2-7a3c2bd88366)

2023-05-12 13:02 UTC, dan-tang-ssd commented
Added email alert for data removal workflow:
 - Requested
 - Reminder (Both manual trigger and daily schedule job trigger)
 - Cancelled
 - Final Confirmed
 - Everything Removed

---

Below please find screen shots FYI:

Requested
![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/74ac0ff8-962a-4691-b5c0-edf0bd39492a)

Reminder
![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/337c4ced-4697-465a-b1fb-096d2b7f9e9c)

Cancelled
![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/ecbc30b3-3b43-4475-9462-bceec2947182)

Final Confirmed
![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/fbd83c29-d9b9-4a45-b01e-9951e21aa6e2)

Everything Removed
![image](https://github.com/stats4sd/aec_portfolio/assets/86968034/c0d356c4-e041-45bf-841a-a9b3c9627206)

2023-05-15 14:21 UTC, dave-mills requested changes
Looks good - I like the carefully considered set of options and functions surrounding the removal of either yourself or the entire institution from the platform. The set of options work well and seem pretty clear to me. 

>  Note: Email template will be developed once confirmed email will be sent for which actions
> P.S. Text content, UI look and feel to be revised

Yep, makes sense. Completely agree to make sure the functionality works and then review the email text, template + UI separately. 

> Currently all operations are performed manually by site admin / site manager.  
As the precise procedure is subject for discussion (this may take a long time). I have developed the core workflow and data removal programs only.

This is excellent. I think it's likely that they'll approve our recommended approach, but with this setup here, we can quickly adjust the final workflow based on any feedback they give. Good work!

Just one small request - I think we should add relationships to link the RemovalRequest model with organistaion and user, and then use that to show the org + requester details in the CRUD panel. Apart from that, this looks good to go.

2023-05-15 14:52 UTC, dan-tang-ssd commented on .env.example
> +DATA_REMOVAL_ALERT_RECIPIENTS=admin@example.com
Yes, very likely.

2023-05-15 14:53 UTC, dan-tang-ssd commented on resources/views/vendor/backpack/base/inc/menu.blade.php
> +        @if ( auth()->user()?->hasRole('Institutional Admin') || auth()->user()?->hasRole('Institutional Assessor') || auth()->user()?->hasRole('Institutional Member') )
Thank you Dave, I have revised as suggested.

2023-05-15 14:53 UTC, dan-tang-ssd commented on resources/views/vendor/backpack/base/inc/sidebar_content.blade.php
> +@if(Auth::user()->can('view institution-level dashboard') || Auth::user()->can('view portfolio-level dashboard') || Auth::user()->can('view project-level dashboard'))
Thank you Dave, I have revised as suggested.

2023-05-15 14:58 UTC, dan-tang-ssd commented on database/migrations/2023_05_11_080031_create_removal_requests_table.php
> +            $table->string('requester_email');
Yes, as the corresonding organisations and users records will be deleted. We will have no model to refer to after "Everything Removed". So I have to copy organisation name, requester name and email when data removal request is submitted. These values will be kept after "Everything Removed" for possible enquiry in future. 

Um... so by definition, can we say everything removed...?

2023-05-15 15:00 UTC, dan-tang-ssd commented on app/Models/RemovalRequest.php
> +
As the corresponding organisation and user model will be deleted, there will be no model to refer to finally.
In this case, do we need to add relationship in model class...?

2023-05-15 15:56 UTC, dave-mills commented on app/Models/RemovalRequest.php
> +
I see your point, but I think the relationship would be long-term more maintainable. (It also means we don't keep data we shouldn't have (e.g. the org name), once the reomval request is completed and actioned.

2023-05-16 08:16 UTC, dan-tang-ssd commented on app/Models/RemovalRequest.php
> +
OK, I will revise program to add the relationships.

2023-05-16 14:22 UTC, dan-tang-ssd commented on app/Http/Controllers/Admin/RemovalRequestCrudController.php
> +        DB::statement('DELETE FROM projects WHERE organisation_id = ' . $organisationId);
Yes, I have just added ON DELETE constraints for most related tables.

One question, will it be possible to delete master records (users) when child records (organisation_members) are deleted. I cannot find out how to do this, so currently I still get all user Ids of an organisation then DELETE them via RAW SQL.

2023-05-18 10:18 UTC, dave-mills approved these changes
Looks great - and the extra constraints + on-delete triggers at the database level is a good solution to clearing out all the organisation's related entries. 👍

2023-05-18 10:18 UTC, dave-mills commented on database/migrations/2023_05_16_100239_add_on_delete_for_organisation_related_tables.php
> +        // Question: Is there any way to delete master records (users) when child records (organisaiton_members) are deleted...?
Not that I know of! A good question... 

I think it's probably fine as-is, though. No need to add something complicated to pro-actively remove those users.

2023-05-18 10:25 UTC, merged